### ISSUE TITLE
Runtime error from jar (NoClassDefFoundError)

### ISSUE THREAD

**Issue by brunocnoliveira** [IBM-i2/Intelligence-Analysis-Platform#5]
Hello,

I have followed carefully the steps to configure and run the da-arload-filesystem-example. It runs perfectly on my Eclipse Kepler. However, when I export the project to JAR file and try to run, the following error is given:

C:\> java -jar da-arload-filesystem-example.jar -load
Exception in thread "main" java.lang.NoClassDefFoundError: com/i2group/apollo/externaldata/loader/IDataLoader  at com.example.ExampleDataLoaderMain.main(ExampleDataLoaderMain.java:57)

Caused by: java.lang.ClassNotFoundException: com.i2group.apollo.externaldata.loader.IDataLoader at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 1 more

The class IDataLoader is aparentely not recognized in the classpath.
I've been trying to fix the problem by many artifices (e.g putting apollo-client-1.0.1.1.jar in root path; declaring the apollo-client-1.0.1.1.jar in MAINFEST, etc.), but got no success yet. Could anyone please give me an idea how to solve this error? 

Thanks,
__
Bruno Oliveira.

**Comment by stu-w** [comment]
Hi, Bruno. Sorry for the delay responding. As this relates to an old release and sounds like a set-up issue I'm going to mark this as closed, but if you're still seeing the issue on the current release then please create a new issue. 

The errors that Eclipse is showing are because it is attempting to validate the WSDL and failing. The WSDL is fine -- it's generated from the endpoint -- so these are spurious errors that you can ignore or you can tell Eclipse not to validate WSDLs (Window > Preferences > Validation > WSDL Validator).

Cheers,
Stu
