### ISSUE TITLE
Error call "purge" method of "da-arload-filesystem-example" project

### ISSUE THREAD

**Issue by mbandeira** [IBM-i2/Intelligence-Analysis-Platform#8]
I am attempting to call "purge" method of "da-arload-filesystem-example" project, but we always receive this error:

com.sun.xml.internal.ws.client.ClientTransportException: The server sent HTTP status code 403: Forbidden
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.checkStatusCode(HttpTransportPipe.java:296)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.createResponsePacket(HttpTransportPipe.java:245)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:203)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:122)
	at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:123)
	at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Fiber.java:626)
	at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Fiber.java:585)
	at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Fiber.java:570)
	at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Fiber.java:467)
	at com.sun.xml.internal.ws.client.Stub.process(Stub.java:308)
	at com.sun.xml.internal.ws.client.sei.SEIStub.doProcess(SEIStub.java:163)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:98)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:135)
	at com.sun.proxy.$Proxy47.purgeItems(Unknown Source)
	at com.i2group.apollo.externaldata.bulkdataloader.serviceproxy.PurgeServiceProxy.purgeItems(PurgeServiceProxy.java:49)
	at com.i2group.apollo.externaldata.bulkdataloader.internal.BulkDataLoaderImplementation.purgeItems(BulkDataLoaderImplementation.java:196)
	at com.i2group.apollo.externaldata.loader.AnalysisRepositoryLoader.purgeItems(AnalysisRepositoryLoader.java:143)
	at com.example.ExampleDataLoader.purge(ExampleDataLoader.java:179)
	at integration.iap.main.IAPIntegration.deleteCaso(IAPIntegration.java:310)
	at integration.iap.main.IAPIntegration.main(IAPIntegration.java:77)

My user has grants level of "UPDATE" and has both " Administrator" and "Admin Security Manager" role in WebSphere (Administrative user roles). I can load (createItems) and sync with no problems. However, when I try to purge the error above occurs.

How can we fix this problem? Have some of you had experienced this error and have any instruction to perform the purge successfully?

**Comment by stu-w** [comment]
I'm marking this as closed as it was with an old version of the product and I believe it was a misconfiguration issue. If you're still having problems with the latest release then do please raise a new issue and we'll investigate.

**Comment by peterforsbergibm** [comment]
I am out of the office until 2015/08/10.




Note: This is an automated response to your message  "Re:
[Intelligence-Analysis-Platform] Error call "purge" method of
"da-arload-filesystem-example" project (#8)" sent on 16/07/2015 17:45:49.

This is the only notification you will receive while this person is away.
