### ISSUE TITLE
DAOD example problem

### ISSUE THREAD

**Issue by jlvila** [IBM-i2/Intelligence-Analysis-Platform#9]
I've just tried 3.0.7 examples and migrate my code from 3.0.5.5 to 3.0.7. All works fine except DAOD.
I've the following error using my DAOD DS:

FROM SILVERLIGHT:
================
The operation was rejected by the server. Try the most recent operation again. If the problem persists, contact your system administrator.i2.Apollo.Common.Exceptions.ValidationException
Data storage partition nearly full (3,440,447,488 bytes free). This can adversely affect system stability. Repository is now read-only until there are at least 4,294,967,296 bytes free. 

System.ServiceModel.FaultException`1[[i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ValidationException, i2.Apollo.Services.Silverlight, Version=3.0.7.0, Culture=neutral, PublicKeyToken=null]]
Data storage partition nearly full (3,440,447,488 bytes free). This can adversely affect system stability. Repository is now read-only until there are at least 4,294,967,296 bytes free.    at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.ClientBase`1.ChannelBase`1.EndInvoke(String methodName, Object[] args, IAsyncResult result)
   at i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ExternalDataSubsetExplorationServiceClient.ExternalDataSubsetExplorationServiceClientChannel.EndSearch(IAsyncResult result)
   at i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ExternalDataSubsetExplorationServiceClient.i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ExternalDataSubsetExplorationService.EndSearch(IAsyncResult result)
   at i2.Apollo.Services.Internal.ExternalDataSubsetExploration.AutoGen.ExternalDataSubsetExplorationServiceClient.i2.Apollo.Services.Internal.ExternalDataSubsetExplorationService.IExternalDataSubsetExplorationServiceInternals.EndSearch(IAsyncResult asyncResult)
   at i2.Apollo.Services.ExternalDataSubsetExplorationService.ExternalDataSubsetExplorationServiceFacade.CompleteAndMarshalSearch(IExternalDataSubsetExplorationServiceInternals client, IAsyncResult resultToken)
   at i2.Apollo.Services.AsynchronousCallCompleter`2.GetResponse(IAsyncResult asyncResult, TResult& successResult, Exception& failureException)

FROM READ SIDE:
==============
2014-12-26 11:12:35,300 - 
com.i2group.apollo.service.common.ValidationException: Data storage partition nearly full (3,440,447,488 bytes free). This can adversely affect system stability. Repository is now read-only until there are at least 4,294,967,296 bytes free.
	at com.i2group.apollo.externaldata.internal.ExternalDataServicesExceptionInterceptor.invoke(ExternalDataServicesExceptionInterceptor.java:81)
	at com.i2group.apollo.service.internal.UserActivityLoggerInterceptor.invoke(UserActivityLoggerInterceptor.java:58)
	at com.i2group.apollo.service.WebServiceFaultCreationInterceptor.invoke(WebServiceFaultCreationInterceptor.java:85)
	at com.i2group.apollo.service.AccessibleScopeInterceptor.invoke(AccessibleScopeInterceptor.java:43)
	at com.i2group.apollo.externaldata.internal.ExternalDataSubsetExplorationServiceDelegateWrapperInternal.search(ExternalDataSubsetExplorationServiceDelegateWrapperInternal.java:216)
	at com.i2group.apollo.externaldatasubsetexplorationservice.internal.ExternalDataSubsetExplorationServiceDelegateWrapper.search(ExternalDataSubsetExplorationServiceDelegateWrapper.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxws.AbstractJAXWSMethodInvoker.invoke(AbstractJAXWSMethodInvoker.java:178)
	at org.apache.cxf.jaxws.JAXWSMethodInvoker.invoke(JAXWSMethodInvoker.java:66)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:75)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:450)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:314)
	at java.util.concurrent.FutureTask.run(FutureTask.java:149)
	at org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:107)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:262)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:211)
	at com.ibm.ws.jaxws.endpoint.AbstractJaxWsWebEndpoint.invoke(AbstractJaxWsWebEndpoint.java:151)
	at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.handleRequest(LibertyJaxWsServlet.java:135)
	at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.doPost(LibertyJaxWsServlet.java:94)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)
	at com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet.service(LibertyJaxWsServlet.java:86)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1275)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:766)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:472)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:135)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:89)
	at com.i2group.apollo.servlet.ResponseCodeFilter.doFilter(ResponseCodeFilter.java:75)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:192)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:86)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:975)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1097)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4797)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:297)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:981)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:262)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:938)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:784)
Caused by: com.i2group.apollo.common.exception.ValidationRuntimeException: Data storage partition nearly full (3,440,447,488 bytes free). This can adversely affect system stability. Repository is now read-only until there are at least 4,294,967,296 bytes free.
	at com.i2group.apollo.common.diskspace.internal.FreeDiskThresholdChecker.throwIfDiskSpaceIsTooLow(FreeDiskThresholdChecker.java:67)
	at com.i2group.apollo.externaldata.infrastructure.internal.FreeDiskThresholdCheckerInterceptor.invoke(FreeDiskThresholdCheckerInterceptor.java:41)
	at com.i2group.apollo.externaldata.infrastructure.internal.SubsetCreator.createSubset(SubsetCreator.java:107)
	at com.i2group.apollo.externaldata.infrastructure.internal.SubsetCreator.createNewSubset(SubsetCreator.java:72)
	at com.i2group.apollo.externaldata.internal.SubsetHelper.initializeSubset(SubsetHelper.java:106)
	at com.i2group.apollo.externaldata.internal.ExternalDataSubsetExplorationServiceFacade.search(ExternalDataSubsetExplorationServiceFacade.java:238)
	at com.i2group.apollo.externaldata.internal.ExternalDataSubsetExplorationServiceDelegate.search(ExternalDataSubsetExplorationServiceDelegate.java:146)
	at com.i2group.apollo.service.AddMetaDataToWebServiceResponseInterceptor.invoke(AddMetaDataToWebServiceResponseInterceptor.java:85)
	at com.i2group.apollo.externaldata.internal.ExternalDataServicesExceptionInterceptor.invoke(ExternalDataServicesExceptionInterceptor.java:70)
	... 46 more

In fact, the value of availabkle storage space is correct but I can't undestand why is a limitation!! How can I change the value of the threshold or remove this validation?

Jean-Louis

**Comment by stu-w** [comment]
Hello, Jean-Louis.

Sorry for the late reply. To prevent system instability, the server automatically prevents new items from being created when server resources fall below a certain level, which is why you're seeing this error. The setting is configurable, though. Add the following property to ApolloServerSettingsCommon.properties:

MinimumFreeDiskSpaceInMegabytes=2048

That will reduce the minimum amount of free space to 2GB; if you'd like to reduce it further then just adjust the number accordingly.

**Comment by peterforsbergibm** [comment]
I am out of the office until 2015/08/10.




Note: This is an automated response to your message  "Re:
[Intelligence-Analysis-Platform] DAOD example problem (#9)" sent on
17/07/2015 10:30:11.

This is the only notification you will receive while this person is away.
